project:
  type: book

book:
  title: "An Introduction to Git and GitHub"
  subtitle: "A Practical Guide for Busy Researchers"
  author: "Callum Arnold"
  date: today
  chapters:
    - index.qmd
    - part: "Prerequisites"
      chapters:
        - git-overview.qmd
        - install-git.qmd
        - github-setup.qmd
        - git-client.qmd
    - part: "Working with Git Fundamentals"
      chapters:
        - how-git-works.qmd
        - making-your-first-repo.qmd
        - git-mechanics.qmd
        - basic-git-workflow.qmd
        - branching-strategies.qmd
        - collaboration.qmd
        - recommended-practices.qmd
    - part: "Troubleshooting Examples"
      chapters:
        - deleting-branches.qmd
        - misc-troubleshooting.qmd
    - todo.qmd
    - references.qmd
  repo-url: https://github.com/arnold-c/psu-intro-to-git
  repo-actions: [edit]
  downloads: [pdf]
  sidebar:
    search: true
    border: true
  google-analytics: "G-EVYBCCRZHE"

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, format/_light.scss]
      dark: [cosmo, format/_dark.scss]
    code-copy: true
    code-fold: false
    code-overflow: wrap
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt



