project:
  type: book

book:
  title: "An Introduction to Git and GitHub"
  subtitle: "A Practical Guide for Busy Researchers"
  author: "Callum Arnold"
  date: today
  chapters:
    - index.qmd
    - part: "Prerequisites"
      chapters:
        - git-overview.qmd
        - install-git.qmd
        - github-setup.qmd
        - git-client.qmd
    - part: "Working with Git"
      chapters:
        - how-git-works.qmd
        - making-your-first-repo.qmd
        - git-mechanics.qmd
        - basic-git-workflow.qmd
        - branching-strategies.qmd
        - recommended-practices.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt



