on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        #with:
        #  tinytex: true
        #env:
        #  GH_TOKEN: ${{ secrets.QUARTO_PUBLISH_TOKEN }}
      - name: Install TinyTex
        run: |
          quarto install tool tinytex
          tlmgr option repository ftp://tug.org/historic/systems/texlive/2023/tlnet-final

      #- name: Render Quarto Project
      #  uses: quarto-dev/quarto-actions/render@v2
          
      - name: Publish HTML book
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: true

